name: verl2
channels:
  - https://repo.anaconda.com/pkgs/main
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=h5eee18b_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - conda-pack=0.8.1=py312h06a4308_0
  - cuda-driver-dev_linux-64=12.4.127=hd681fbe_0
  - cuda-version=12.4=hbda6634_3
  - dbus=1.16.2=h5bd4931_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - gds-tools=1.9.1.3=h99ab3db_1
  - gmp=6.3.0=h6a678d5_0
  - icu=73.1=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libcufft=11.2.1.3=h99ab3db_1
  - libcufft-dev=11.2.1.3=h99ab3db_1
  - libcufile=1.9.1.3=h99ab3db_1
  - libcufile-dev=1.9.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurand-dev=10.3.5.147=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libcusparse-dev=12.3.1.170=h99ab3db_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.84.4=h77a78f3_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libkrb5=1.21.3=h520c7b4_4
  - libnpp=12.2.5.30=h99ab3db_1
  - libnpp-dev=12.2.5.30=h99ab3db_1
  - libnvfatbin=12.4.127=h7934f7d_2
  - libnvfatbin-dev=12.4.127=h7934f7d_2
  - libnvjitlink=12.4.127=h99ab3db_1
  - libnvjitlink-dev=12.4.127=h99ab3db_1
  - libnvjpeg=12.3.1.117=h6a678d5_1
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxkbfile=1.1.0=hf54ef8a_2
  - libxml2=2.13.9=h2c43086_0
  - lmdb=0.9.31=hb25bd0a_0
  - nccl=2.28.7=h2db5b60_0
  - ncurses=6.5=h7934f7d_0
  - nsight-compute=2024.1.1.4=h669d3df_3
  - nspr=4.37=h8459abe_0
  - nss=3.89.1=h6a678d5_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openmpi=5.0.8=hdd5af13_0
  - openssl=3.0.18=hd6dcaed_0
  - pcre2=10.46=hf426167_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.12=hc23ea64_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py312h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h9b100fa_2
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxtst=1.2.5=h9b100fa_3
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=hd233ad5_2
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - addict==2.4.0
      - aenum==3.1.16
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiohttp-cors==0.8.1
      - aiosignal==1.4.0
      - airportsdata==20250909
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.71.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - apache-tvm-ffi==0.1.4
      - apex==0.1
      - astor==0.8.1
      - asttokens==3.0.0
      - attrdict==2.0.1
      - attrs==25.4.0
      - av==15.1.0
      - awscli==1.43.5
      - awscli-plugin-endpoint==0.4
      - backoff==2.2.1
      - binpacking==1.5.2
      - blake3==1.0.8
      - blinker==1.9.0
      - blobfile==3.1.0
      - botocore==1.41.5
      - brotli==1.1.0
      - build==1.4.0
      - cachetools==6.2.4
      - cbor2==5.8.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - cfgv==3.4.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - click-option-group==0.5.9
      - cloudpickle==3.1.2
      - codetiming==1.4.0
      - colorama==0.4.6
      - colored==2.3.1
      - colorful==0.5.7
      - compressed-tensors==0.12.2
      - contourpy==1.3.3
      - cpm-kernels==1.0.11
      - crcmod==1.7
      - cryptography==46.0.2
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.3.1
      - cuda-python==13.1.1
      - cuda-toolkit==13.0.0
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - dacite==1.9.2
      - datasets==3.1.0
      - decorator==5.2.1
      - decord==0.6.0
      - deprecated==1.2.18
      - depyf==0.20.0
      - diffusers==0.36.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - docutils==0.19
      - einops==0.8.1
      - email-validator==2.3.0
      - et-xmlfile==2.0.0
      - etcd3==0.12.0
      - evaluate==0.4.6
      - executing==2.2.1
      - fastapi==0.128.0
      - fastapi-cli==0.0.20
      - fastapi-cloud-cli==0.3.1
      - fastar==0.8.0
      - fastrlock==0.8.3
      - fastuuid==0.13.5
      - ffmpy==0.6.3
      - filelock==3.20.3
      - flash-attn==2.7.4+cu128torch2.9
      - flashinfer-cubin==0.5.3
      - flashinfer-python==0.3.1.post1
      - flask==3.1.2
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - future==1.0.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.26.0
      - google-auth==2.41.1
      - googleapis-common-protos==1.70.0
      - gradio==5.49.1
      - gradio-client==1.13.3
      - groovy==0.1.2
      - grpcio==1.75.1
      - gurobipy==13.0.0
      - h11==0.16.0
      - h5py==3.12.1
      - hf-transfer==0.1.9
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - identify==2.6.15
      - idna==3.11
      - ijson==3.4.0.post0
      - importlib-metadata==8.0.0
      - iniconfig==2.1.0
      - interegular==0.3.3
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jieba==0.42.1
      - jinja2==3.1.6
      - jiter==0.12.0
      - jmespath==0.10.0
      - joblib==1.5.2
      - json-repair==0.53.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lark==1.2.2
      - liger-kernel==0.6.2
      - lightning-utilities==0.15.2
      - litellm==1.78.0
      - llguidance==0.7.29
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - lxml==6.0.2
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mathruler==0.1.0
      - matplotlib==3.10.7
      - matplotlib-inline==0.1.7
      - mcp==1.26.0
      - mdurl==0.1.2
      - meson==1.10.1
      - mistral-common==1.8.6
      - ml-dtypes==0.5.4
      - model-hosting-container-standards==0.1.13
      - modelscope==1.30.0
      - mpi==1.0.0
      - mpi4py==4.1.1
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - nanobind==2.9.2
      - narwhals==2.15.0
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - ninja==1.13.0
      - nltk==3.9.2
      - nodeenv==1.9.1
      - numba==0.61.2
      - numexpr==2.13.1
      - numpy==1.26.4
      - nvidia-cublas==13.0.0.19
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti==13.0.48
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc==13.0.48
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime==13.0.48
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cudnn-frontend==1.17.0
      - nvidia-cufft==12.0.0.15
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile==1.15.0.42
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand==10.4.0.35
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver==12.0.3.29
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse==12.6.2.49
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-cutlass-dsl==4.3.4
      - nvidia-ml-py==13.580.82
      - nvidia-modelopt==0.37.0
      - nvidia-modelopt-core==0.29.0
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nccl-cu13==2.27.7
      - nvidia-nvjitlink==13.0.39
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvshmem-cu13==3.3.24
      - nvidia-nvtx==13.0.39
      - nvidia-nvtx-cu12==12.8.90
      - nvtx==0.2.14
      - omegaconf==2.3.0
      - onnx==1.19.1
      - onnx-graphsurgeon==0.5.8
      - onnx-ir==0.1.14
      - onnxscript==0.5.7
      - openai==2.15.0
      - openai-harmony==0.0.4
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-fixer==0.2.5
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - opentelemetry-api==1.26.0
      - opentelemetry-exporter-otlp==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-exporter-otlp-proto-grpc==1.26.0
      - opentelemetry-exporter-otlp-proto-http==1.26.0
      - opentelemetry-exporter-prometheus==1.12.0rc1
      - opentelemetry-proto==1.26.0
      - opentelemetry-sdk==1.26.0
      - opentelemetry-semantic-conventions==0.47b0
      - opentelemetry-semantic-conventions-ai==0.4.13
      - optimum==2.1.0
      - optree==0.17.0
      - ordered-set==4.1.0
      - orjson==3.11.3
      - oss2==2.19.1
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==26.0
      - pandarallel==1.6.5
      - pandas==2.3.3
      - parso==0.8.5
      - partial-json-parser==0.2.1.1.post6
      - patchelf==0.18.0.0
      - peft==0.17.1
      - pexpect==4.9.0
      - pillow==12.1.0
      - pip==25.3
      - platformdirs==4.5.0
      - plotly==6.5.2
      - pluggy==1.6.0
      - polygraphy==0.49.26
      - pre-commit==4.3.0
      - prometheus-client==0.24.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==4.25.8
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pulp==3.3.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - py-spy==0.4.1
      - pyarrow==19.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.3
      - pybind11==3.0.1
      - pycountry==24.6.1
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pycryptodomex==3.23.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.6
      - pydantic-settings==2.12.0
      - pydub==0.25.1
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pylatexenc==2.10
      - pynvml==13.0.1
      - pyparsing==3.2.5
      - pyproject-hooks==1.2.0
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.21
      - pytorch-lightning==2.5.5
      - pytz==2025.2
      - pyvers==0.1.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qwen-vl-utils==0.0.8
      - ray==2.41.0
      - rdkit==2025.9.1
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - rich==14.1.0
      - rich-toolkit==0.15.1
      - rignore==0.7.0
      - rouge==1.0.1
      - rpds-py==0.30.0
      - rsa==4.7.2
      - ruff==0.14.0
      - s3transfer==0.15.0
      - safehttpx==0.1.6
      - safetensors==0.7.0
      - scipy==1.17.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.50.0
      - setproctitle==1.3.7
      - setuptools==79.0.1
      - sgl-kernel==0.1.0
      - sglang==0.4.6.post1
      - shellingham==1.5.4
      - simplejson==3.20.2
      - six==1.17.0
      - smart-open==7.3.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soundfile==0.13.1
      - sse-starlette==3.2.0
      - stack-data==0.6.3
      - starlette==0.50.0
      - strenum==0.4.15
      - supervisor==4.3.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensordict==0.10.0
      - tensorrt==10.13.3.9.post1
      - tensorrt-cu12==10.13.3.9
      - tensorrt-cu12-bindings==10.13.3.9
      - tensorrt-cu12-libs==10.13.3.9
      - tensorrt-cu13==10.13.3.9.post1
      - tensorrt-cu13-bindings==10.13.3.9.post1
      - tensorrt-cu13-libs==10.13.3.9.post1
      - tensorrt-llm==1.2.0rc8
      - tiktoken==0.12.0
      - tokenizers==0.22.2
      - tomlkit==0.13.3
      - torch==2.9.0+cu128
      - torch-c-dlpack-ext==0.1.3
      - torch-memory-saver==0.0.8
      - torchao==0.15.0
      - torchaudio==2.9.0+cu128
      - torchdata==0.11.0
      - torchmetrics==1.8.2
      - torchprofile==0.0.4
      - torchtext==0.6.0
      - torchvision==0.24.0+cu128
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformer-engine-cu12==2.11.0
      - transformer-engine-torch==2.11.0
      - transformers==4.57.1
      - transformers-stream-generator==0.0.5
      - triton==3.5.0
      - trl==0.20.0
      - typer==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.6.3
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - verl==0.8.0.dev0
      - virtualenv==20.35.0
      - wandb==0.22.2
      - watchfiles==1.1.0
      - wcwidth==0.2.14
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - xformers==0.0.33.post1
      - xgrammar==0.1.25
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: /mnt/shared-storage-user/mineru4s/dingruiyi/anaconda/envs/verl2
